module.exports = (pkg) => {
    const todayDateTime = new Date().toString();
    const banner =
`/*
 * THIS FILE HAS BEEN GENERATED BY AN AUTOMATED TOOL.
 * DO NOT MODIFY DIRECTLY. INSTEAD MODIFY THE APPROPRIATE SOURCE CODE.
 *
 * ${pkg.name} v${pkg.version}
 * ${pkg.description}
 * Development By: ${pkg.developedBy}
 * Build Date: ${todayDateTime}
 */
`;
    return banner;
};
